import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";

import { useAccount } from "wagmi";

const Home: NextPage = () => {
  const { isConnected } = useAccount();

  return (
    <div>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      {/* HEADER */}
      <div className="px-3 py-4">
        <span>Some Company Logo</span>
      </div>

      <main className="flex items-center justify-center flex-col text-center min-h-[90vh]">
        {isConnected ? (
          <div>
            <ConnectButton />
            <div>You are connected</div>
          </div>
        ) : (
          <div>
            <p>Start your journey by connecting your wallet</p>
            <ConnectButton />
          </div>
        )}
      </main>

      <footer className="flex px-5 items-center justify-center">
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Kayaga Web3 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
